version: "3"
services:
    jupyter:
        image: occam-aims-lib
        build: docker/jupyter
        container_name: jupyter
        environment:
            - "PYTHONPATH=/opt/lib/python"
        env_file: docker/jupyter/.env
        ports:
            - "8888:8888"
        volumes:
            - "./data:/opt/data"
            - "./src:/opt/lib/python/src"
            - "./notebooks:/opt/work"
